name: Build Docker

on: push
env:
  NODE_VERSION: "v16.4.2"
  TIMEOUT: "1m"

jobs:
  configure:
    name: Configure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Configure 
        run: |
          docker buildx build \
            --push \
            --build-arg NODE_VERSION=${NODE_VERSION} \
            --target configure \
            -t ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial .

  make-1:
    name: Make 1
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - if: failure()
        run: | 
          echo "BUILD_FAIL=true" >> $GITHUB_ENV

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

  make-2:
    name: Make 2
    needs: make-1
    if: env.BUILD_FAIL == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

  make-3:
    name: Make 3
    needs: make-2
    if: env.BUILD_FAIL == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - if: failure()
        run: | 
          echo "BUILD_FAIL=true" >> $GITHUB_ENV

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

  make-4:
    name: Make 4
    needs: make-3
    if: env.BUILD_FAIL == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - if: failure()
        run: | 
          echo "BUILD_FAIL=true" >> $GITHUB_ENV

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

  make-5:
    name: Make 5
    needs: make-4
    if: env.BUILD_FAIL == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - if: failure()
        run: | 
          echo "BUILD_FAIL=true" >> $GITHUB_ENV

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

  make-6:
    name: Make 6
    needs: make-5
    if: env.BUILD_FAIL == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - if: failure()
        run: | 
          echo "BUILD_FAIL=true" >> $GITHUB_ENV

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

  make-7:
    name: Make 7
    needs: make-6
    if: env.BUILD_FAIL == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - if: failure()
        run: | 
          echo "BUILD_FAIL=true" >> $GITHUB_ENV

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

  make-8:
    name: Make 8
    needs: make-7
    if: env.BUILD_FAIL == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - if: failure()
        run: | 
          echo "BUILD_FAIL=true" >> $GITHUB_ENV

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

  make-9:
    name: Make 9
    needs: make-8
    if: env.BUILD_FAIL == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - if: failure()
        run: | 
          echo "BUILD_FAIL=true" >> $GITHUB_ENV

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

  make-10:
    name: Make 10
    needs: make-9
    if: env.BUILD_FAIL == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - if: failure()
        run: | 
          echo "BUILD_FAIL=true" >> $GITHUB_ENV

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

  make-11:
    name: Make 11
    needs: make-10
    if: env.BUILD_FAIL == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - if: failure()
        run: | 
          echo "BUILD_FAIL=true" >> $GITHUB_ENV

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

  make-12:
    name: Make 12
    needs: make-11
    if: env.BUILD_FAIL == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Make
        continue-on-error: true
        run: |
          docker run --name sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial sh -c "timeout $TIMEOUT make -j $(nproc); exit"

      - if: failure()
        run: | 
          echo "BUILD_FAIL=true" >> $GITHUB_ENV

      - name: Docker Commit
        run: |
          docker container commit sn-container ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial
          docker image push ${{ secrets.DOCKER_REPO }}:${NODE_VERSION}-x64-partial

          